version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      APP_DB_USER: "docker"
      APP_DB_PASS: "docker"
      APP_DB_NAME: "knewin"
    ports:
      - "15432:5432"
    volumes:
      - ./docker-compose/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - postgresql
volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
  postgresql:
    driver: bridge
